[[decks]]
id = "it_basic"
display_name = "Italian: Language Transfer"
spreadsheet_id = "1AMQ68lGQUxVcNtapkB8bhgnyYyn6MrFQvrRWRJ_l6mg"
worksheet_name = "Language Transfer"

[[decks]]
id = "it_phrases"
display_name = "Italian: Phrases"
spreadsheet_id = "1AMQ68lGQUxVcNtapkB8bhgnyYyn6MrFQvrRWRJ_l6mg"
worksheet_name = "Phrases"

[[decks]]
id = "zh_hsk1"
display_name = "Chinese: Duolingo"
spreadsheet_id = "104ptZ30KpS9hP4JOuFl5wf2z5leN7DickYvzwno0GMs"
worksheet_name = "Vocab"
font_size_px = 42 # Large font configuration for mobile readability

[[decks]]
id = "zh_hsk2"
display_name = "Chinese: Old Vocab"
spreadsheet_id = "104ptZ30KpS9hP4JOuFl5wf2z5leN7DickYvzwno0GMs"
worksheet_name = "Old Vocab"
font_size_px = 42 # Large font configuration for mobile readability

